### ISSUE TITLE
bottom navigation bar problem ( still not working )

### ISSUE THREAD

**Issue by marwasoumia** [WaelMohamedKhelil/mobile-Projet2cs#6]
as data is brought from the api , the bottom navigation bar doesnt work in the correct way

**Comment by marwasoumia** [comment]
@WaelMohamedKhelil

**Comment by WaelMohamedKhelil** [comment]
Can you explain more

**Comment by marwasoumia** [comment]
i really don't know where's the source of the problem ( did not inspect it yet ) but its not working means  that when you try to go to notification or profile or search fragment from main fragment through bottom bar  it doesn't go / you can check what's im saying on the current version of code in master

**Comment by WaelMohamedKhelil** [comment]
This problem has been occurred after the gradle dependencies update or before that?

**Comment by marwasoumia** [comment]
after that , [but i canceled the gradle update i've done i've just changed MinApi ]

**Comment by WaelMohamedKhelil** [comment]
I have already tried to fix it, I didn't find any problem, I think it works.

**Comment by marwasoumia** [comment]
i tried it on two devices ( api 22 and api 23 ) , can u try it on Apu24 or  above ? maybe the ui element doesnt work correctly on less than 24
