### ISSUE TITLE
Adding confirmation dialog once click on command button in configure ui

### ISSUE THREAD

**Issue by marwasoumia** [WaelMohamedKhelil/mobile-Projet2cs#9]
Once user clicks on command button in configure ui , i want to display two dialogs : 
the first one ask if the user is sure and has two buttons : confirmer , annuler 
if "confirmer" : 
execute lines 118-125 in configureDialogFragment.kt
display another dialog which displays the result message and has one button OK

**Comment by marwasoumia** [comment]
@WaelMohamedKhelil  please try to add them , it's simple i just dont manage ui stuffs thank you

**Comment by WaelMohamedKhelil** [comment]
Done
